<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW4J24Dt\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW4J24Dt/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerW4J24Dt.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerW4J24Dt\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerW4J24Dt\App_KernelProdContainer([
    'container.build_hash' => 'W4J24Dt',
    'container.build_id' => 'c363e569',
    'container.build_time' => 1766587249,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW4J24Dt');
