<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKKT9acb\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKKT9acb/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerKKT9acb.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerKKT9acb\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerKKT9acb\App_KernelProdContainer([
    'container.build_hash' => 'KKT9acb',
    'container.build_id' => 'ed9919b8',
    'container.build_time' => 1766502966,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKKT9acb');
