<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNTvZgsT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNTvZgsT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNTvZgsT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNTvZgsT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNTvZgsT\App_KernelDevDebugContainer([
    'container.build_hash' => 'NTvZgsT',
    'container.build_id' => 'f7e0ece3',
    'container.build_time' => 1766592928,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNTvZgsT');
